import React, {Component} from 'react';
import PropTypes from "prop-types";
import {StyleSheet, Text, View, TextInput, FlatList, Picker, ScrollView, TouchableHighlight} from 'react-native';
import {Image as ReactImage} from 'react-native';
import Svg, {Defs, Pattern} from 'react-native-svg';
import {Path as SvgPath} from 'react-native-svg';
import {Text as SvgText} from 'react-native-svg';
import {Image as SvgImage} from 'react-native-svg';

export default class Singlereconcile extends Component {

  constructor(props) {
      super(props);
      this.state = {
          
      };
  }


  handlePress(target, owner) {
    if (this.props.onPress) {
        let name;
        let id;
        let index = -1;
        if (target.search("::") > -1) {
            const varCount = target.split("::").length;
            if (varCount === 2) {
                name = target.split("::")[0];
                id = target.split("::")[1];
            } else if (varCount === 3) {
                name = target.split("::")[0];
                index = parseInt(target.split("::")[1]);
                id = target.split("::")[2];
            }
        } else {
            name = target;
        }
        this.props.onPress({ type: 'button', name: name, index: index, id: id, owner: owner });
    }
  }

  handleChangeTextinput(name, value) {
      let id;
      let index = -1;
      if (name.search('::') > -1) {
          const varCount = name.split("::").length;
          if (varCount === 2) {
              name = name.split("::")[0];
              id = name.split("::")[1];
          } else if (varCount === 3) {
              name = name.split("::")[0];
              index = name.split("::")[1];
              id = name.split("::")[2];
          }
      } else {
          name = name;
      }
      let state = this.state;
      state[name.split('::').join('')] = value;
      this.setState(state, () => {
          if (this.props.onChange) {
              this.props.onChange({ type: 'textinput', name: name, value: value, index: index, id: id });
          }
      });
  }

  render() {
    
    return (
    <ScrollView data-layer="cd69ac0c-29fb-45f9-bed1-67181bfa3f2b" style={styles.singlereconcile}>
        <View data-layer="607ce331-9bc4-44b5-8bfa-8404da1b4a64" style={styles.singlereconcile_bodycontainer}>
            <View data-layer="8725118a-9934-4cc2-92c1-0a3d563d9561" style={styles.singlereconcile_bodycontainer_twobuttoncontainer}>
                <View data-layer="9746c7c1-ca73-475d-8d05-e9c435fe3f74" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_rightbutton}>
                    <View data-layer="677cc46b-5af3-4454-a69a-32ab3e5530f8" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1}>
                        <View data-layer="32029099-4aac-4211-944c-490a86472107" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1_rightuttonlayer2}>
                            <View data-layer="130d92cd-ee58-4de5-8250-d070349b67e5" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1_rightuttonlayer2_lightElevation02dpfc04e959}>
                                <View data-layer="28ff2484-9891-4168-a30c-1139051282a6" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1_rightuttonlayer2_lightElevation02dpfc04e959_shadow5e829af6}>
                                    <View data-layer="eac5bbb3-898d-47af-96e8-1b50660386fd" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1_rightuttonlayer2_lightElevation02dpfc04e959_shadow5e829af6_rectangle751889d3}></View>
                                    <View data-layer="91431bdf-0e97-4c57-82a8-b1002e0ec73a" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1_rightuttonlayer2_lightElevation02dpfc04e959_shadow5e829af6_rectangle70a1336c}></View>
                                    <View data-layer="f2a25e59-318b-49ce-94b1-807cfb471f51" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1_rightuttonlayer2_lightElevation02dpfc04e959_shadow5e829af6_rectanglecdc5404b}></View>
                                </View>
                            </View>
                            <View data-layer="2b3ab17b-96b1-4fbc-8663-d9a9d39eb39f" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1_rightuttonlayer2_xColor153a0d35}></View>
                            <View data-layer="c0c189cf-7560-4b9b-a24a-7ce089ce1173" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1_rightuttonlayer2_xStates757b12c0}>
                                <View data-layer="2845691d-9301-4ac8-a7a2-b7a40deeb78a" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1_rightuttonlayer2_xStates757b12c0_stateslightPrimaryContainer100overlay6851659d}></View>
                            </View>
                        </View>
                    </View>
                    <Text data-layer="fa69db84-efe8-4ba5-9307-a52877ec5f0e" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_xLabelf97cd87f}>UPDATE</Text>
                </View>
                <View data-layer="3a0987aa-6680-4faf-bbfc-ac497a119e78" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_leftbutton}>
                    <View data-layer="54284c27-8947-4ee5-9f9f-a8a16339028b" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1}>
                        <View data-layer="21ace861-f9a9-4076-8cd0-cd6b12699de2" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1_leftbuttonlayer2}>
                            <View data-layer="479b8a59-aad6-4f62-9987-7e3f02fa205a" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1_leftbuttonlayer2_lightElevation02dpb2ff721c}>
                                <View data-layer="29d4029c-61a8-45de-8edd-cc9f59d32e6a" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1_leftbuttonlayer2_lightElevation02dpb2ff721c_shadowc77d1537}>
                                    <View data-layer="780f4271-7099-472d-a92a-02bd029cf824" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1_leftbuttonlayer2_lightElevation02dpb2ff721c_shadowc77d1537_rectanglee408a721}></View>
                                    <View data-layer="3848d8b5-85e8-4956-834d-0b199cb3eb99" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1_leftbuttonlayer2_lightElevation02dpb2ff721c_shadowc77d1537_rectangle03d792ed}></View>
                                    <View data-layer="d7364d61-c4c5-4208-ae79-04d28930f3fb" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1_leftbuttonlayer2_lightElevation02dpb2ff721c_shadowc77d1537_rectangle1f467508}></View>
                                </View>
                            </View>
                            <View data-layer="3a4290cb-9f5b-4cf2-9dc9-f33d2bfb3a83" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1_leftbuttonlayer2_xColord1a9ad35}></View>
                            <View data-layer="3553cc8b-c5c7-47d3-99f9-64ecb357741e" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1_leftbuttonlayer2_xStates972ff37d}>
                                <View data-layer="21c7e2df-8d19-41c0-a24b-32fc0ce77291" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1_leftbuttonlayer2_xStates972ff37d_stateslightPrimaryContainer100overlay8d5b1dc3}></View>
                            </View>
                        </View>
                    </View>
                    <Text data-layer="06d66f07-8a92-4891-885c-c1df24f89593" style={styles.singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_xLabel7f1527ab}>UPDATE</Text>
                </View>
            </View>
            <View data-layer="cbe8e6ec-5d45-4b52-80d0-e02e3776c125" style={styles.singlereconcile_bodycontainer_labelcontainer}>
                <View data-layer="3225da64-ba7e-45f1-ba4f-797c67cbd734" style={styles.singlereconcile_bodycontainer_labelcontainer_labelelevation}>
                    <Svg data-layer="746e800b-1bd8-428f-b9f8-5087597da892" style={styles.singlereconcile_bodycontainer_labelcontainer_labelelevation_color24d7c285} preserveAspectRatio="none" viewBox="0 0 12 7.399993896484375" fill="rgba(252, 244, 244, 1)"><SvgPath d="M 10.59000015258789 0 L 6 4.573819160461426 L 1.409999966621399 0 L 0 1.408097147941589 L 6 7.400000095367432 L 12 1.408097147941589 L 10.59000015258789 0 Z"  /></Svg>
                </View>
                <View data-layer="dd304d95-e048-48dc-80fc-1c5aaa0e6ae5" style={styles.singlereconcile_bodycontainer_labelcontainer_label2ndlayercontainer}>
                    <View data-layer="9de1aca4-c285-4433-86c5-5bd0c3d51585" style={styles.singlereconcile_bodycontainer_labelcontainer_label2ndlayercontainer_label3rdlayercontainer}>
                        <Svg data-layer="b5c43243-4f34-4f17-9f10-4ed142f4a8ff" style={styles.singlereconcile_bodycontainer_labelcontainer_label2ndlayercontainer_label3rdlayercontainer_xColor576c49ee} preserveAspectRatio="none" viewBox="-0.75 -0.75 367.5 37.5" fill="rgba(56, 156, 196, 1)"><SvgPath d="M 4 0 L 362 0 C 364.2091369628906 0 366 1.790860891342163 366 4 L 366 32 C 366 34.20914077758789 364.2091369628906 36 362 36 L 4 36 C 1.790860891342163 36 0 34.20914077758789 0 32 L 0 4 C 0 1.790860891342163 1.790860891342163 0 4 0 Z"  /></Svg>
                        <View data-layer="9ed08b65-457f-48e7-94c8-43d64328347f" style={styles.singlereconcile_bodycontainer_labelcontainer_label2ndlayercontainer_label3rdlayercontainer_xStates0a6affa0}>
                            <View data-layer="c9e070e7-2eed-49ec-8f1f-960a472db962" style={styles.singlereconcile_bodycontainer_labelcontainer_label2ndlayercontainer_label3rdlayercontainer_xStates0a6affa0_stateslightSurfaceContainersprimaryContent}></View>
                        </View>
                    </View>
                </View>
                <Text data-layer="8c11d235-2b6f-4a73-b501-353f0804edaf" style={styles.singlereconcile_bodycontainer_labelcontainer_labeltextcontainer}>Medication details</Text>
                <View data-layer="28fd32fa-f228-4b1b-afd5-48e5bdb110a5" style={styles.singlereconcile_bodycontainer_labelcontainer_labelicon}>
                    <Svg data-layer="f034a50b-9938-4c83-86cb-97838da285a1" style={styles.singlereconcile_bodycontainer_labelcontainer_labelicon_color526457ec} preserveAspectRatio="none" viewBox="0 0 12 7.399993896484375" fill="rgba(252, 244, 244, 1)"><SvgPath d="M 10.59000015258789 0 L 6 4.573819160461426 L 1.409999966621399 0 L 0 1.408097147941589 L 6 7.400000095367432 L 12 1.408097147941589 L 10.59000015258789 0 Z"  /></Svg>
                </View>
            </View>
            <View data-layer="f6068078-a5db-4fd2-8520-68cbe542e8da" style={styles.singlereconcile_bodycontainer_hallfinputcontainer}>
                <View data-layer="6e6a20ef-6643-451d-9c78-a63d1fd8bad5" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_leftinput}>
                    <View data-layer="f8dd7a74-1d0e-499f-b629-f07815625f93" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_leftinput_lightElevation00dp5d66d5ac}>
                        <View data-layer="34f37c8b-d0a6-4439-9fd7-270d1fa51a25" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_leftinput_lightElevation00dp5d66d5ac_rectangle1c40fe6c}></View>
                    </View>
                    <View data-layer="5cc6f262-4803-42c3-918a-c87b66fffaa2" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_leftinput_xContainerLColorffd26aff}></View>
                    <View data-layer="c7d4f6d0-52b2-4477-abdb-95e40ef63508" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55}>
                        <View data-layer="a36caffc-742b-4409-a1b1-33689ba0ea13" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_states5e0b2822}></View>
                        <View data-layer="82f5a5ee-7481-4e80-baf5-d0bf35a8c694" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_indicator2764b1bd}></View>
                        <Text data-layer="68ec4cb9-11c6-4210-9b29-569fbe1c4167" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_xLabel6fb1af24}>Refills left *</Text>
                        <View data-layer="88e4a071-4d19-4228-aad0-5d8af010ebca" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_lightListssingleLinebody2WRightIcon}>
                            <View data-layer="3c862d8d-0af4-4d41-b728-8f80e150705a" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_lightListssingleLinebody2WRightIcon_iconnavigationarrowdropdown24px}>
                                <View data-layer="886c8414-0088-4753-b6ef-13f71c906598" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_lightListssingleLinebody2WRightIcon_iconnavigationarrowdropdown24px_boundary94e82b9e}></View>
                                <Svg data-layer="13b110ec-c034-41aa-aec4-c5168152264b" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_lightListssingleLinebody2WRightIcon_iconnavigationarrowdropdown24px_color53db9b04} preserveAspectRatio="none" viewBox="0 0 10 5" fill="rgba(0, 0, 0, 1)"><SvgPath d="M 0 0 L 5 5 L 10 0 L 0 0 Z"  /></Svg>
                            </View>
                            <Text data-layer="b925eb18-9ab9-45f7-875f-30bab8586156" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_lightListssingleLinebody2WRightIcon_xSubtitle1}>1</Text>
                        </View>
                    </View></View>
                <View data-layer="a88ffbb9-e797-4386-970b-b612f12a9f81" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_rightinput}>
                    <View data-layer="baefb8f1-3e7c-4d3e-9018-b70ca95e0386" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_rightinput_lightElevation00dp35bcad65}>
                        <View data-layer="0f9a8e52-7cd4-4009-a0f1-3c519466ea22" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_rightinput_lightElevation00dp35bcad65_rectangleb50b839b}></View>
                    </View>
                    <View data-layer="3761c6f0-d453-4b82-88c7-4524dee36bee" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_rightinput_xContainerLColor29a9ebca}></View>
                    <View data-layer="856b23f2-479c-428f-99a8-687288777f46" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_rightinput_group1cdd30935}>
                        <View data-layer="7564fde4-40dd-4766-8d00-3063014a83a5" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_rightinput_group1cdd30935_states7cd431bc}></View>
                        <View data-layer="0c6f9b06-3228-43d5-b27d-646c2d703b26" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_rightinput_group1cdd30935_indicator56413741}></View>
                        <Text data-layer="da886fb1-623f-48aa-b77c-ba0b019610b0" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_rightinput_group1cdd30935_xLabele5af0479}>Date Refilled *</Text>
                    </View>
                    <Text data-layer="5bfd2081-c119-4f3d-bc8a-5c5a060d404b" style={styles.singlereconcile_bodycontainer_hallfinputcontainer_rightinput_xInputText6a0a76e9}>mm/dd/yyyy</Text>
                </View>
            </View>
            <View data-layer="0c2eef8d-3923-43e3-a4a4-ef437d136fe0" style={styles.singlereconcile_bodycontainer_fullinputcontainer}>
                <View data-layer="beeab6dc-c9c7-45e0-bf4d-59c73a4b8457" style={styles.singlereconcile_bodycontainer_fullinputcontainer_lightElevation00dp}>
                    <View data-layer="b6115b71-74fa-41e7-a2b5-c69a147294e8" style={styles.singlereconcile_bodycontainer_fullinputcontainer_lightElevation00dp_rectangleb0c5f9e4}></View>
                </View>
                <View data-layer="77862100-b316-45a5-af7b-2eec7dce09bc" style={styles.singlereconcile_bodycontainer_fullinputcontainer_xContainerLColord1c272d0}></View>
                <View data-layer="71ef25a5-656b-4884-b395-e0a01be66c60" style={styles.singlereconcile_bodycontainer_fullinputcontainer_group1}>
                    <View data-layer="8376f954-f7b8-4ca7-95b2-52231ca7e1f6" style={styles.singlereconcile_bodycontainer_fullinputcontainer_group1_states}></View>
                    <View data-layer="b62817eb-33a7-498f-b774-853c13024ed7" style={styles.singlereconcile_bodycontainer_fullinputcontainer_group1_indicator}></View>
                    <Text data-layer="18f458f0-7447-45e4-a473-acf944de2d43" style={styles.singlereconcile_bodycontainer_fullinputcontainer_group1_xInputText}>Name of medicine</Text>
                    <Text data-layer="e793267b-94a7-49ba-904d-5ad71848683d" style={styles.singlereconcile_bodycontainer_fullinputcontainer_group1_xLabel3826c82e}>Name of Medicine *</Text>
                </View></View>
            <View data-layer="e4d0b7ca-2740-44bc-bbac-d1fdf594c03d" style={styles.singlereconcile_bodycontainer_editslipcontainer}>
                <View data-layer="5f93ef9e-ee2f-45a7-b8f4-d484e816c179" style={styles.singlereconcile_bodycontainer_editslipcontainer_slipimagecontainer}>
                    <View data-layer="390c1433-c36f-45fa-8636-1ae2898d6b65" style={styles.singlereconcile_bodycontainer_editslipcontainer_slipimagecontainer_lightCardelementsImageaimage}>
                        <ReactImage data-layer="73d316f4-d9a0-4a54-be4b-dfa9a03f1efe" source={require('./assets/xImage.png')} style={styles.singlereconcile_bodycontainer_editslipcontainer_slipimagecontainer_lightCardelementsImageaimage_xImage} />
                        <View data-layer="7d36f27c-a2d3-49e9-98d0-70e8bdec7d3d" style={styles.singlereconcile_bodycontainer_editslipcontainer_slipimagecontainer_lightCardelementsImageaimage_xStates34abe0cd}></View>
                    </View></View>
                <View data-layer="7459ee42-4b82-439d-84fa-3558199f2844" style={styles.singlereconcile_bodycontainer_editslipcontainer_editcontainer}>
                    <View data-layer="f15fb70c-1800-40ad-8569-66c1b3ee8818" style={styles.singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer}>
                        <View data-layer="3627a20f-0737-4a68-8400-9e439fbb2f8e" style={styles.singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled}>
                            <View data-layer="f863adec-1497-43db-907c-53cc47f1df69" style={styles.singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled_editinnercontainer}>
                                <View data-layer="c1c61ecb-9189-4849-9930-f5673cc0e06c" style={styles.singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled_editinnercontainer_lightElevation02dp}>
                                    <View data-layer="6cbf58e8-f3eb-4a47-819f-7a01b64ad37c" style={styles.singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled_editinnercontainer_lightElevation02dp_shadow}>
                                        <View data-layer="b113a46d-c46b-48f9-9f9f-c5b0f1c1ed23" style={styles.singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled_editinnercontainer_lightElevation02dp_shadow_rectanglecc09ae1a}></View>
                                        <View data-layer="7a059ac2-d7b7-4321-b097-a79b985b0c76" style={styles.singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled_editinnercontainer_lightElevation02dp_shadow_rectangle518b8f0a}></View>
                                        <View data-layer="d7d84991-d8de-43aa-bda8-3851960ebcfb" style={styles.singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled_editinnercontainer_lightElevation02dp_shadow_rectangle}></View>
                                    </View>
                                </View>
                                <View data-layer="9bcca197-0dc8-48c3-a3d5-e73c2b336f94" style={styles.singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled_editinnercontainer_xColor}></View>
                                <View data-layer="a7a0ace7-03ea-420f-ab56-a3b90c6f1926" style={styles.singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled_editinnercontainer_xStates}>
                                    <View data-layer="8efa0d61-01a4-4ff5-aacf-13870f17239e" style={styles.singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled_editinnercontainer_xStates_stateslightPrimaryContainer100overlay}></View>
                                </View>
                            </View>
                        </View>
                        <ReactImage data-layer="907566bd-4771-4a19-abc9-be807a3c6e60" source={require('./assets/editicon.png')} style={styles.singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_editicon} />
                    </View>
                </View>
            </View>
        </View>
    </ScrollView>
    );
  }
}

Singlereconcile.propTypes = {

}

Singlereconcile.defaultProps = {

}


const styles = StyleSheet.create({
  "singlereconcile": {
    "opacity": 1,
    "position": "relative",
    "backgroundColor": "rgba(255, 255, 255, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 414,
    "height": 736,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 375,
    "height": 409,
    "left": 20,
    "top": 81
  },
  "singlereconcile_bodycontainer_twobuttoncontainer": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 375,
    "height": 35,
    "left": 0,
    "top": 374
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_rightbutton": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 126,
    "height": 35,
    "left": 249,
    "top": 0
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 126,
    "height": 35,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1_rightuttonlayer2": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 126,
    "height": 35,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1_rightuttonlayer2_lightElevation02dpfc04e959": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 126,
    "height": 35,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1_rightuttonlayer2_lightElevation02dpfc04e959_shadow5e829af6": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 126,
    "height": 35,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1_rightuttonlayer2_lightElevation02dpfc04e959_shadow5e829af6_rectangle751889d3": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(34, 171, 226, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(0, 0, 0, 0)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(0, 0, 0, 0)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(0, 0, 0, 0)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(0, 0, 0, 0)",
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 4,
    "borderBottomRightRadius": 4,
    "shadowColor": "rgb(0,  0,  0)",
    "shadowOpacity": 0.2,
    "shadowOffset": {
      "width": 0,
      "height": 1
    },
    "shadowRadius": 5,
    "width": 125,
    "height": 34,
    "left": -0.5,
    "top": -0.5
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1_rightuttonlayer2_lightElevation02dpfc04e959_shadow5e829af6_rectangle70a1336c": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(34, 171, 226, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(0, 0, 0, 0)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(0, 0, 0, 0)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(0, 0, 0, 0)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(0, 0, 0, 0)",
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 4,
    "borderBottomRightRadius": 4,
    "shadowColor": "rgb(0,  0,  0)",
    "shadowOpacity": 0.12156862745098039,
    "shadowOffset": {
      "width": 0,
      "height": 3
    },
    "shadowRadius": 1,
    "width": 125,
    "height": 34,
    "left": -0.5,
    "top": -0.5
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1_rightuttonlayer2_lightElevation02dpfc04e959_shadow5e829af6_rectanglecdc5404b": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(34, 171, 226, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(0, 0, 0, 0)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(0, 0, 0, 0)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(0, 0, 0, 0)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(0, 0, 0, 0)",
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 4,
    "borderBottomRightRadius": 4,
    "shadowColor": "rgb(0,  0,  0)",
    "shadowOpacity": 0.1411764705882353,
    "shadowOffset": {
      "width": 0,
      "height": 2
    },
    "shadowRadius": 2,
    "width": 125,
    "height": 34,
    "left": -0.5,
    "top": -0.5
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1_rightuttonlayer2_xColor153a0d35": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(34, 171, 226, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 4,
    "borderBottomRightRadius": 4,
    "width": 126,
    "height": 35,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1_rightuttonlayer2_xStates757b12c0": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 126,
    "height": 35,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_rightbuttonlayer1_rightuttonlayer2_xStates757b12c0_stateslightPrimaryContainer100overlay6851659d": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(34, 171, 226, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(0, 0, 0, 0)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(0, 0, 0, 0)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(0, 0, 0, 0)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(0, 0, 0, 0)",
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 4,
    "borderBottomRightRadius": 4,
    "width": 125,
    "height": 34,
    "left": -0.5,
    "top": -0.5
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_rightbutton_xLabelf97cd87f": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(255, 255, 255, 1)",
    "fontSize": 14,
    "fontWeight": "500",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "lineHeight": 16,
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 56,
    "height": 21,
    "left": 35,
    "top": 9.5
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_leftbutton": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 126,
    "height": 35,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 126,
    "height": 35,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1_leftbuttonlayer2": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 126,
    "height": 35,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1_leftbuttonlayer2_lightElevation02dpb2ff721c": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 126,
    "height": 35,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1_leftbuttonlayer2_lightElevation02dpb2ff721c_shadowc77d1537": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 126,
    "height": 35,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1_leftbuttonlayer2_lightElevation02dpb2ff721c_shadowc77d1537_rectanglee408a721": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(34, 171, 226, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(0, 0, 0, 0)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(0, 0, 0, 0)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(0, 0, 0, 0)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(0, 0, 0, 0)",
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 4,
    "borderBottomRightRadius": 4,
    "shadowColor": "rgb(0,  0,  0)",
    "shadowOpacity": 0.2,
    "shadowOffset": {
      "width": 0,
      "height": 1
    },
    "shadowRadius": 5,
    "width": 125,
    "height": 34,
    "left": -0.5,
    "top": -0.5
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1_leftbuttonlayer2_lightElevation02dpb2ff721c_shadowc77d1537_rectangle03d792ed": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(34, 171, 226, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(0, 0, 0, 0)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(0, 0, 0, 0)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(0, 0, 0, 0)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(0, 0, 0, 0)",
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 4,
    "borderBottomRightRadius": 4,
    "shadowColor": "rgb(0,  0,  0)",
    "shadowOpacity": 0.12156862745098039,
    "shadowOffset": {
      "width": 0,
      "height": 3
    },
    "shadowRadius": 1,
    "width": 125,
    "height": 34,
    "left": -0.5,
    "top": -0.5
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1_leftbuttonlayer2_lightElevation02dpb2ff721c_shadowc77d1537_rectangle1f467508": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(34, 171, 226, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(0, 0, 0, 0)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(0, 0, 0, 0)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(0, 0, 0, 0)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(0, 0, 0, 0)",
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 4,
    "borderBottomRightRadius": 4,
    "shadowColor": "rgb(0,  0,  0)",
    "shadowOpacity": 0.1411764705882353,
    "shadowOffset": {
      "width": 0,
      "height": 2
    },
    "shadowRadius": 2,
    "width": 125,
    "height": 34,
    "left": -0.5,
    "top": -0.5
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1_leftbuttonlayer2_xColord1a9ad35": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(34, 171, 226, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 4,
    "borderBottomRightRadius": 4,
    "width": 126,
    "height": 35,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1_leftbuttonlayer2_xStates972ff37d": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 126,
    "height": 35,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_leftbuttonlayer1_leftbuttonlayer2_xStates972ff37d_stateslightPrimaryContainer100overlay8d5b1dc3": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(34, 171, 226, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(0, 0, 0, 0)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(0, 0, 0, 0)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(0, 0, 0, 0)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(0, 0, 0, 0)",
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 4,
    "borderBottomRightRadius": 4,
    "width": 125,
    "height": 34,
    "left": -0.5,
    "top": -0.5
  },
  "singlereconcile_bodycontainer_twobuttoncontainer_leftbutton_xLabel7f1527ab": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(255, 255, 255, 1)",
    "fontSize": 14,
    "fontWeight": "500",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "lineHeight": 16,
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 56,
    "height": 21,
    "left": 35,
    "top": 9.5
  },
  "singlereconcile_bodycontainer_labelcontainer": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 366,
    "height": 36,
    "left": 4,
    "top": 220
  },
  "singlereconcile_bodycontainer_labelcontainer_labelelevation": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 12,
    "height": 7.4,
    "left": 17,
    "top": 14.6
  },
  "singlereconcile_bodycontainer_labelcontainer_labelelevation_color24d7c285": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 12,
    "height": 7.4,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_labelcontainer_label2ndlayercontainer": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 366,
    "height": 36,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_labelcontainer_label2ndlayercontainer_label3rdlayercontainer": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 366,
    "height": 36,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_labelcontainer_label2ndlayercontainer_label3rdlayercontainer_xColor576c49ee": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 366,
    "height": 36,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_labelcontainer_label2ndlayercontainer_label3rdlayercontainer_xStates0a6affa0": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 0,
    "height": 0,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_labelcontainer_label2ndlayercontainer_label3rdlayercontainer_xStates0a6affa0_stateslightSurfaceContainersprimaryContent": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(17, 102, 141, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(0, 0, 0, 0)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(0, 0, 0, 0)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(0, 0, 0, 0)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(0, 0, 0, 0)",
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 4,
    "borderBottomRightRadius": 4,
    "width": -1,
    "height": -1,
    "left": -0.5,
    "top": -0.5
  },
  "singlereconcile_bodycontainer_labelcontainer_labeltextcontainer": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(252, 244, 244, 1)",
    "fontSize": 14,
    "fontWeight": "500",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "lineHeight": 16,
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 157,
    "height": 21,
    "left": 40,
    "top": 11.5
  },
  "singlereconcile_bodycontainer_labelcontainer_labelicon": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 12,
    "height": 7.4,
    "left": 17,
    "top": 14.6
  },
  "singlereconcile_bodycontainer_labelcontainer_labelicon_color526457ec": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 12,
    "height": 7.4,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_hallfinputcontainer": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 363,
    "height": 60,
    "left": 4,
    "top": 307
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 174,
    "height": 60,
    "left": 189,
    "top": 0
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_lightElevation00dp5d66d5ac": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 174,
    "height": 56,
    "left": 0,
    "top": 4
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_lightElevation00dp5d66d5ac_rectangle1c40fe6c": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 174,
    "height": 56,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_xContainerLColorffd26aff": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(0, 0, 0, 0.043137254901960784)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 174,
    "height": 56,
    "left": 0,
    "top": 4
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 174,
    "height": 60,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_states5e0b2822": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0.12156862745098039)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 174,
    "height": 56,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_indicator2764b1bd": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(34, 171, 226, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 174,
    "height": 2,
    "left": 0,
    "top": 58
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_xLabel6fb1af24": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(34, 171, 226, 1)",
    "fontSize": 12,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "lineHeight": 16,
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 64,
    "height": 20,
    "left": 16,
    "top": 11
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_lightListssingleLinebody2WRightIcon": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 35,
    "height": 24,
    "left": 16,
    "top": 27
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_lightListssingleLinebody2WRightIcon_xElevation": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(0, 0, 0, 0)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(0, 0, 0, 0)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(0, 0, 0, 0)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(0, 0, 0, 0)",
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 66,
    "height": 31,
    "left": -16.5,
    "top": -4.5
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_lightListssingleLinebody2WRightIcon_lightDevider": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 51,
    "height": 1,
    "left": 0,
    "top": 27
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_lightListssingleLinebody2WRightIcon_lightDevider_deviderLight": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(0, 0, 0, 0.12156862745098039)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 51,
    "height": 1,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_lightListssingleLinebody2WRightIcon_iconnavigationarrowdropdown24px": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 24,
    "height": 24,
    "left": 11,
    "top": 0
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_lightListssingleLinebody2WRightIcon_iconnavigationarrowdropdown24px_boundary94e82b9e": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 24,
    "height": 24,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_lightListssingleLinebody2WRightIcon_iconnavigationarrowdropdown24px_color53db9b04": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 10,
    "height": 5,
    "left": 7,
    "top": 10
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_lightListssingleLinebody2WRightIcon_states5ae25593": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(0, 0, 0, 0)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(0, 0, 0, 0)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(0, 0, 0, 0)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(0, 0, 0, 0)",
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 66,
    "height": 31,
    "left": -16.5,
    "top": -4.5
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_group170fb5a55_lightListssingleLinebody2WRightIcon_xSubtitle1": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 0.8705882352941177)",
    "fontSize": 14,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "lineHeight": 20,
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 8,
    "height": 25,
    "left": 0,
    "top": 1.5
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_leadingIcone6672ec3": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 24,
    "height": 24,
    "left": 16,
    "top": 20
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_leadingIcone6672ec3_boundary16de7640": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 24,
    "height": 24,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_leftinput_leadingIcone6672ec3_colora9e72889": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 20,
    "height": 18,
    "left": 2,
    "top": 3
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_rightinput": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 174,
    "height": 60,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_rightinput_lightElevation00dp35bcad65": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 174,
    "height": 56,
    "left": 0,
    "top": 4
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_rightinput_lightElevation00dp35bcad65_rectangleb50b839b": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 174,
    "height": 56,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_rightinput_xContainerLColor29a9ebca": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(0, 0, 0, 0.043137254901960784)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 174,
    "height": 56,
    "left": 0,
    "top": 4
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_rightinput_group1cdd30935": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 174,
    "height": 60,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_rightinput_group1cdd30935_states7cd431bc": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0.12156862745098039)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 174,
    "height": 56,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_rightinput_group1cdd30935_indicator56413741": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(34, 171, 226, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 174,
    "height": 2,
    "left": 0,
    "top": 58
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_rightinput_group1cdd30935_xLabele5af0479": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(34, 171, 226, 1)",
    "fontSize": 12,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "lineHeight": 16,
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 81,
    "height": 20,
    "left": 16,
    "top": 11
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_rightinput_leadingIcon8add72a9": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 24,
    "height": 24,
    "left": 16,
    "top": 20
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_rightinput_leadingIcon8add72a9_boundary186fde14": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 24,
    "height": 24,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_rightinput_leadingIcon8add72a9_colorffb6022a": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 20,
    "height": 18,
    "left": 2,
    "top": 3
  },
  "singlereconcile_bodycontainer_hallfinputcontainer_rightinput_xInputText6a0a76e9": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 0.6)",
    "fontSize": 16,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "lineHeight": 24,
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 91,
    "height": 29,
    "left": 15,
    "top": 27.5
  },
  "singlereconcile_bodycontainer_fullinputcontainer": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 366,
    "height": 60,
    "left": 4,
    "top": 250
  },
  "singlereconcile_bodycontainer_fullinputcontainer_lightElevation00dp": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 366,
    "height": 56,
    "left": 0,
    "top": 4
  },
  "singlereconcile_bodycontainer_fullinputcontainer_lightElevation00dp_rectangleb0c5f9e4": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 366,
    "height": 56,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_fullinputcontainer_xContainerLColord1c272d0": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(0, 0, 0, 0.043137254901960784)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 366,
    "height": 56,
    "left": 0,
    "top": 4
  },
  "singlereconcile_bodycontainer_fullinputcontainer_group1": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 366,
    "height": 60,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_fullinputcontainer_group1_states": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0.12156862745098039)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 366,
    "height": 56,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_fullinputcontainer_group1_indicator": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(34, 171, 226, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 366,
    "height": 2,
    "left": 0,
    "top": 58
  },
  "singlereconcile_bodycontainer_fullinputcontainer_group1_xInputText": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 0.6)",
    "fontSize": 16,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "lineHeight": 24,
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 132,
    "height": 29,
    "left": 16,
    "top": 24.5
  },
  "singlereconcile_bodycontainer_fullinputcontainer_group1_xLabel3826c82e": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(34, 171, 226, 1)",
    "fontSize": 12,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "lineHeight": 16,
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 113,
    "height": 20,
    "left": 16,
    "top": 12
  },
  "singlereconcile_bodycontainer_fullinputcontainer_leadingIcon": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 24,
    "height": 24,
    "left": 16,
    "top": 20
  },
  "singlereconcile_bodycontainer_fullinputcontainer_leadingIcon_boundary9cbb4a96": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 24,
    "height": 24,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_fullinputcontainer_leadingIcon_colorec601e05": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 20,
    "height": 18,
    "left": 2,
    "top": 3
  },
  "singlereconcile_bodycontainer_editslipcontainer": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 375,
    "height": 209,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_editslipcontainer_slipimagecontainer": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 375,
    "height": 209,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_editslipcontainer_slipimagecontainer_lightCardelementsImageaimage": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 375,
    "height": 209,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_editslipcontainer_slipimagecontainer_lightCardelementsImageaimage_xImage": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 375,
    "height": 209,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_editslipcontainer_slipimagecontainer_lightCardelementsImageaimage_xStates34abe0cd": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(0, 0, 0, 0)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(0, 0, 0, 0)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(0, 0, 0, 0)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(0, 0, 0, 0)",
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 374,
    "height": 208,
    "left": -0.5,
    "top": -0.5
  },
  "singlereconcile_bodycontainer_editslipcontainer_slipimagecontainer_lightImageLists2FooteraOverlay": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 375,
    "height": 48,
    "left": 0,
    "top": 161
  },
  "singlereconcile_bodycontainer_editslipcontainer_slipimagecontainer_lightImageLists2FooteraOverlay_xContainerLColor": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(0, 0, 0, 0.3803921568627451)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 375,
    "height": 48,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_editslipcontainer_slipimagecontainer_lightImageLists2FooteraOverlay_xLabel": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(255, 255, 255, 0.8705882352941177)",
    "fontSize": 16,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "lineHeight": 24,
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 68,
    "height": 29,
    "left": 16,
    "top": 11.5
  },
  "singlereconcile_bodycontainer_editslipcontainer_slipimagecontainer_lightImageLists2FooteraOverlay_iconactionfavorite24px": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 24,
    "height": 24,
    "left": 339,
    "top": 12
  },
  "singlereconcile_bodycontainer_editslipcontainer_slipimagecontainer_lightImageLists2FooteraOverlay_iconactionfavorite24px_boundary": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 24,
    "height": 24,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_editslipcontainer_slipimagecontainer_lightImageLists2FooteraOverlay_iconactionfavorite24px_color": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 20,
    "height": 18,
    "left": 2,
    "top": 3
  },
  "singlereconcile_bodycontainer_editslipcontainer_editcontainer": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 48,
    "height": 28,
    "left": 327,
    "top": 0
  },
  "singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 48,
    "height": 28,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 48,
    "height": 28,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled_editinnercontainer": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 48,
    "height": 28,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled_editinnercontainer_lightElevation02dp": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 48,
    "height": 28,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled_editinnercontainer_lightElevation02dp_shadow": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 48,
    "height": 28,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled_editinnercontainer_lightElevation02dp_shadow_rectanglecc09ae1a": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(34, 171, 226, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(0, 0, 0, 0)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(0, 0, 0, 0)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(0, 0, 0, 0)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(0, 0, 0, 0)",
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 4,
    "borderBottomRightRadius": 4,
    "shadowColor": "rgb(0,  0,  0)",
    "shadowOpacity": 0.2,
    "shadowOffset": {
      "width": 0,
      "height": 1
    },
    "shadowRadius": 5,
    "width": 47,
    "height": 27,
    "left": -0.5,
    "top": -0.5
  },
  "singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled_editinnercontainer_lightElevation02dp_shadow_rectangle518b8f0a": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(34, 171, 226, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(0, 0, 0, 0)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(0, 0, 0, 0)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(0, 0, 0, 0)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(0, 0, 0, 0)",
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 4,
    "borderBottomRightRadius": 4,
    "shadowColor": "rgb(0,  0,  0)",
    "shadowOpacity": 0.12156862745098039,
    "shadowOffset": {
      "width": 0,
      "height": 3
    },
    "shadowRadius": 1,
    "width": 47,
    "height": 27,
    "left": -0.5,
    "top": -0.5
  },
  "singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled_editinnercontainer_lightElevation02dp_shadow_rectangle": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(34, 171, 226, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(0, 0, 0, 0)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(0, 0, 0, 0)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(0, 0, 0, 0)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(0, 0, 0, 0)",
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 4,
    "borderBottomRightRadius": 4,
    "shadowColor": "rgb(0,  0,  0)",
    "shadowOpacity": 0.1411764705882353,
    "shadowOffset": {
      "width": 0,
      "height": 2
    },
    "shadowRadius": 2,
    "width": 47,
    "height": 27,
    "left": -0.5,
    "top": -0.5
  },
  "singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled_editinnercontainer_xColor": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(34, 171, 226, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 4,
    "borderBottomRightRadius": 4,
    "width": 48,
    "height": 28,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled_editinnercontainer_xStates": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 48,
    "height": 28,
    "left": 0,
    "top": 0
  },
  "singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_lightButton3ContainedaTextenabled_editinnercontainer_xStates_stateslightPrimaryContainer100overlay": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(34, 171, 226, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(0, 0, 0, 0)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(0, 0, 0, 0)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(0, 0, 0, 0)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(0, 0, 0, 0)",
    "borderTopLeftRadius": 4,
    "borderTopRightRadius": 4,
    "borderBottomLeftRadius": 4,
    "borderBottomRightRadius": 4,
    "width": 47,
    "height": 27,
    "left": -0.5,
    "top": -0.5
  },
  "singlereconcile_bodycontainer_editslipcontainer_editcontainer_edit2ndlayer_editicon": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 24,
    "height": 24,
    "left": 12,
    "top": 2
  }
});